../rtl/core/fp_pkg.sv
../rtl/core/fp_unpack.sv
../rtl/core/fp_round_pack.sv
../rtl/core/fp_sgnj.sv
../rtl/core/fp_cmp.sv
../rtl/core/fp_fma.sv
../rtl/core/fp_divsqrt.sv
../rtl/core/fp_cvt.sv
../rtl/core/icg.v
../rtl/core/pc.v
../rtl/core/register_file.v
../rtl/core/imm_gen.v
../rtl/core/alu.v
../rtl/core/control_unit.v
../rtl/core/csr_file.v
../rtl/core/fpr.v
../rtl/core/fp_alu.v
../rtl/core/riscv_top.v
../rtl/mem/imem.v
../rtl/mem/dmem.v
../tb/top/tb_arch_test.sv
../rtl/core/pipe_if_id.v
../rtl/core/pipe_id_ex.v
../rtl/core/pipe_ex_mem.v
../rtl/core/pipe_mem_wb.v
../rtl/core/forwarding_unit.v
../rtl/core/hazard_unit.v
