../rtl/core/fp_pkg.sv
../rtl/core/fp_unpack.sv
../rtl/core/fp_round_pack.sv
../rtl/core/fp_sgnj.sv
../rtl/core/fp_cmp.sv
../rtl/core/fp_fma.sv
../rtl/core/fp_divsqrt.sv
../rtl/core/fp_cvt.sv
../rtl/core/alu.v
../rtl/core/icg.v
../rtl/core/register_file.v
../rtl/core/imm_gen.v
../rtl/core/pc.v
../rtl/core/control_unit.v
../rtl/mem/imem.v
../rtl/mem/dmem.v
../rtl/core/riscv_top.v
../tb/top/tb_riscv_top.sv
../rtl/core/csr_file.v

../rtl/core/fpr.v
../rtl/core/fp_alu.v
